### ISSUE TITLE
"Kotlin: Indexing" is always displayed

### ISSUE THREAD

**Issue by yihaoBeta** [fwcd/kotlin-language-server#403]
when I open a Kotlin project  build with gradle,the "Kotlin:Indexing" information is always displayed,and never disappear

here some infos may help:
* Macbook pro (10.15.7)
* java version:11.0.4.1
* kotlin version: 1.7.20
* gradle:7.5

**Comment by themkat** [comment]
Which editor are you using? Have you checked the language server output to see that the server is actually done? (dropdown menu item called Kotlin in the Output section in VSCode, `*lsp-log*` in Emacs etc.).  Some bigger projects take time to load. When it is actually done it will print "Updated full symbol index in x ms!" (where x is how long it took). 


Also, are you using the latest version? An issue relating to this was fixed before summer, and was caused by the done-event never being sent.

**Comment by yihaoBeta** [comment]
> Which editor are you using? Have you checked the language server output to see that the server is actually done? (dropdown menu item called Kotlin in the Output section in VSCode, `*lsp-log*` in Emacs etc.). Some bigger projects take time to load. When it is actually done it will print "Updated full symbol index in x ms!" (where x is how long it took).
> 
> Also, are you using the latest version? An issue relating to this was fixed before summer, and was caused by the done-event never being sent.

Hi,my editor is vscode(1.72.1) with the lastest version of kotlin-language-server, and the project is just a initial project create by "gradle init"
[The log file](https://github.com/fwcd/kotlin-language-server/files/9781750/log.txt)

**Comment by themkat** [comment]
I don't see the "Updated full symbol index in.." log message that happens when it is done with the indexing. Have you waited at least 5-10 minutes and checked that it still says "Indexing"? Seems weird that it suddenly just stops. Nothing in the logs that indicate any errors. The log statement at the bottom mentions an Android class, is this an Android project? Those usually take some time to load in my experience 🙁

**Comment by yihaoBeta** [comment]
It is not a Android project,but I installed Android Studio.
I re-tested and the test lasted 15 minutes, and the same problem remains.
But I got some error logs this time.
Hope these will help.
[log.txt](https://github.com/fwcd/kotlin-language-server/files/9791051/log.txt)

**Comment by themkat** [comment]
Early in the logs I see this `Caused by: java.lang.OutOfMemoryError: Java heap space` for the first error you get. After that I see errors of the H2 database that the symbol index uses not finding the expected table. Never experienced this before 😨  Maybe you could try increasing the heap size a bit? My guess is that you have a small maximum heap size. The internal symbol index of the language server uses a shitload of RAM (even smaller projects have a lot of standard library symbols).
