### ISSUE TITLE
Unresolved references for standard library dependencies

### ISSUE THREAD

**Issue by Gouvernathor** [fwcd/kotlin-language-server#610]
When writing `mapOf<Any, Any>()`, mapOf is underlined with `Unresolved reference: mapOf` `kotlin(UNRESOLVED_REFERENCE)`.
Despite mapOf being in the standard imports of the standard library. Same with `sequence` and `listOf`.

I have kotlinc version 2.1.0 and java version 23.0.1.

**Comment by Decodetalkers** [comment]
I think I have solve this problem, https://github.com/mykotlinlab/kotlin-language-server, I made a fork myself, because the first fork also inactive

This is because the bug in old exposed, it existed under version 0.40, and kts use 0.33. And if kts cannot insert data to the database, it will throw all the depencies. And, yes, it will always throw the error, and made the editor all red. now it is solved in my fork.

Maybe you can take a try to my fork

**Comment by Gouvernathor** [comment]
Following recent commits, mapOf now seems to work, but imports from `kotlin.test` all fail. Maybe it's unrelated.

**Comment by rubin55** [comment]
> Following recent commits, mapOf now seems to work, but imports from `kotlin.test` all fail. Maybe it's unrelated.

This is exactly right; I've tested this with both vscode and emacs, and in both cases, any "test" dependency (i.e., `testImplementation` and `androidTestImplementation` under `dependencies` in `build.gradle`) does not resolve and indicates an `UNRESOLVED_REFERENCE` error.
